AjaxCRUDProject/Models/Employee.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace AjaxCRUDProject.Models
{
    public class Employee
    {
        [Key]
        public int Id { get; set; }
        [Required(ErrorMessage ="Bạn chưa nhập tên")]
        [DisplayName("Tên")]
        [Column(TypeName ="nvarchar(20)")]
        public string Name { get; set; }
        
        [Required(ErrorMessage = "Bạn chưa nhập địa chỉ")]
        [DisplayName("Địa chỉ")]
        [Column(TypeName = "nvarchar(100)")]
        public string Address { get; set; }

        [Required(ErrorMessage = "Bạn chưa nhập Email")]
        [DisplayName("Email")]
        [Column(TypeName = "nvarchar(100)")]
        [EmailAddress(ErrorMessage = "Email không hợp lệ")]
        public string Email { get; set; }

        [Required(ErrorMessage = "Bạn chưa nhập số điện thoại")]
        [DisplayName("Số điện thoại")]
        [Column(TypeName = "nvarchar(11)")]
        [RegularExpression("([0][0-9]+)", ErrorMessage = "Nhập đúng số điện thoại")]
        [StringLength(10, MinimumLength  = 10, ErrorMessage = "Số điện thoại phải có 10 số")]
        public string Phone { get; set; }
        public DateTime CreatedDateTime { get; set; } = DateTime.Now;
    }
}

AjaxCRUDProject/Models/ErrorViewModel.cs
namespace AjaxCRUDProject.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AjaxCRUDProject/Controllers/EmployeesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AjaxCRUDProject.Data;
using AjaxCRUDProject.Models;

namespace AjaxCRUDProject.Controllers
{
    public class EmployeesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public EmployeesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Employees
        public async Task<IActionResult> Index()
        {
              return _context.Employees != null ? 
                          View(await _context.Employees.ToListAsync()) :
                          Problem("Entity set 'ApplicationDbContext.Employees'  is null.");
        }

        // GET: Employees/Details/5
        
        // GET: Employees/AddOrEdit
        // GET: Employees/AddOrEdit/5
        public async Task<IActionResult> AddOrEdit(int id = 0)
        {
            if(id==0)
                return View(new Employee());
            else
            {
                var employee = await _context.Employees.FindAsync(id);
                if (employee == null)
                {
                    return NotFound();
                }
                return View(employee);
            }
        }

        // POST: Employees/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Address,Email,Phone,CreatedDateTime")] Employee employee)
        {
            if (ModelState.IsValid)
            {
                _context.Add(employee);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(employee);
        }

        // GET: Employees/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Employees == null)
            {
                return NotFound();
            }

            var employee = await _context.Employees.FindAsync(id);
            if (employee == null)
            {
                return NotFound();
            }
            return View(employee);
        }

        // POST: Employees/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddOrEdit(int id, [Bind("Id,Name,Address,Email,Phone,CreatedDateTime")] Employee employee)
        {
            

            if (ModelState.IsValid)
            {
                if(id == 0)
                {
                    _context.Add(employee);
                    await _context.SaveChangesAsync();
                }
                else
                {
                    try
                    {
                        _context.Update(employee);
                        await _context.SaveChangesAsync();
                    }
                    catch (DbUpdateConcurrencyException)
                    {
                        if (!EmployeeExists(employee.Id))
                        {
                            return NotFound();
                        }
                        else
                        {
                            throw;
                        }
                    }
                }
                return Json(new { isValid = true, html = Helper.RenderRazorViewToString(this,"_ViewAll",_context.Employees.ToList()) });
            }
            return Json(new {isValid = false, html = Helper.RenderRazorViewToString(this, "AddOrEdit", employee) });
        }

        // GET: Employees/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Employees == null)
            {
                return NotFound();
            }

            var employee = await _context.Employees
                .FirstOrDefaultAsync(m => m.Id == id);
            if (employee == null)
            {
                return NotFound();
            }

            return View(employee);
        }

        // POST: Employees/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Employees == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Employees'  is null.");
            }
            var employee = await _context.Employees.FindAsync(id);
            if (employee != null)
            {
                _context.Employees.Remove(employee);
            }
            
            await _context.SaveChangesAsync();
            return Json(new { html = Helper.RenderRazorViewToString(this, "_ViewAll", _context.Employees.ToList()) });
        }

        private bool EmployeeExists(int id)
        {
          return (_context.Employees?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

AjaxCRUDProject/Controllers/HomeController.cs
using AjaxCRUDProject.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace AjaxCRUDProject.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

AjaxCRUDProject/Views/Employees/AddOrEdit.cshtml
@model AjaxCRUDProject.Models.Employee

@{
    ViewData["Title"] = "Edit";
    Layout = null;
}


<div class="row">
    <div class="col-md-12">
        <form asp-action="AddOrEdit" asp-route-id="@Model.Id"  onsubmit=" return jQueryAjaxPost(this);" autocomplete="off">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />

            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Phone" class="control-label"></label>
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary btn-block" />
            </div>
        </form>
        <div>
            <a onclick="hidePopup('@Url.Action("Index","Employees",Context.Request.Scheme)')" class="btn btn-secondary btn-block">Close</a>
        </div>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AjaxCRUDProject/Views/Employees/Create.cshtml
@model AjaxCRUDProject.Models.Employee

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Employee</h4>
<hr />
<div class="row">
    <div class="col-md-12">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Phone" class="control-label"></label>
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CreatedDateTime" class="control-label"></label>
                <input asp-for="CreatedDateTime" class="form-control" />
                <span asp-validation-for="CreatedDateTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AjaxCRUDProject/Views/Employees/Delete.cshtml
@model AjaxCRUDProject.Models.Employee

@{
    ViewData["Title"] = "Delete"#view-all
    Layout = null;
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Employee</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-4">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-12">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-4">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class = "col-sm-12">
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt class = "col-sm-4">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-12">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-4">
            @Html.DisplayNameFor(model => model.Phone)
        </dt>
        <dd class = "col-sm-12">
            @Html.DisplayFor(model => model.Phone)
        </dd>
    </dl>
    
    <form asp-action="Delete" asp-route-id="@Model.Id" onsubmit="    return jQueryAjaxDelete(this);" class="d-inline">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <!-- <a asp-action="Index">Back to List</a> --> 
    </form>
    <a onclick="hidePopup('@Url.Action("Index","Employees",Context.Request.Scheme)')" class="btn btn-secondary">Close</a>
</div>

AjaxCRUDProject/Views/Employees/Index.cshtml
@model IEnumerable<AjaxCRUDProject.Models.Employee>

@{
    ViewData["Title"] = "Index";
}

<h1 class="text-center">Employee</h1>

<div id="view-all">
    @await Html.PartialAsync("_ViewAll",Model)
</div>

AjaxCRUDProject/Views/Employees/_ViewAll.cshtml
@model IEnumerable<AjaxCRUDProject.Models.Employee>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Address)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Phone)
            </th>
            <th>
                <a onclick="showPopup('@Url.Action("AddOrEdit","Employees",new{id=0},Context.Request.Scheme)','New Employee')" class="btn btn-success">Create New</a>
            </th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Phone)
            </td>
            <td>
                <a onclick="showPopup('@Url.Action("AddOrEdit","Employees",new{id = item.Id},Context.Request.Scheme)','Update Employee')" class="btn btn-secondary">Edit</a>|
                <a onclick="showPopup('@Url.Action("Delete","Employees",new{id = item.Id},Context.Request.Scheme)','Delete Employee')" class="btn btn-danger">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

AjaxCRUDProject/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

AjaxCRUDProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AjaxCRUDProject</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AjaxCRUDProject.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AjaxCRUDProject</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employees" asp-action="Index">Employees</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <div class="modal" tabindex="-1" role="dialog" id="form-modal">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title">Modal title</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close" onclick="hidePopup('@Url.Action("Index","Employees",Context.Request.Scheme)')">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            
          </div>
          
        </div>
      </div>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - AjaxCRUDProject - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/alert.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>